name: TimeCMA_Qwen3
channels:
  - defaults  
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.0.0
      - accelerate==1.11.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - cachetools==5.3.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - deepspeed==0.18.3
      - easy-torch==1.3.2
      - easydict==1.10
      - einops==0.7.0
      - filelock==3.9.0
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - huggingface-hub==0.36.0
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.1
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpi4py==4.1.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.0.4
      - networkx==3.0
      - ninja==1.13.0
      - numexpr==2.10.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.2.2
      - packaging==23.1
      - pandas==2.3.3
      - pillow==9.3.0
      - propcache==0.4.1
      - protobuf==4.23.4
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.1.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.4
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.6.2
      - scikit-learn==1.0.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - setproctitle==1.3.2
      - setuptools==59.5.0
      - six==1.17.0
      - sympy==1.14.0
      - tables==3.7.0
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - vmdpy==0.2
      - werkzeug==3.1.3
      - yarl==1.22.0
prefix: /root/anaconda3/envs/TimeCMA_Qwen3
